/** Generated by scripts/render-structures.mjs — do not edit. Products with a rendered 2D structure in public/structures/svg. */
export const STRUCTURE_INDEX: Record<string, { formula?: string; mw?: string }> = {
 "guaifenesin": {
  "formula": "C10H14O4",
  "mw": "198.22"
 },
 "methocarbamol": {
  "formula": "C11H15NO5",
  "mw": "241.24"
 },
 "mephenesin": {
  "formula": "C10H14O3",
  "mw": "182.22"
 },
 "chlorphenesin-carbamate": {
  "formula": "C10H12ClNO4",
  "mw": "245.66"
 },
 "mebeverine-hydrochloride": {
  "formula": "C25H36ClNO5",
  "mw": "466.0"
 },
 "ranolazine": {
  "formula": "C24H33N3O4",
  "mw": "427.5"
 },
 "benfotiamine": {
  "formula": "C19H23N4O6PS",
  "mw": "466.4"
 },
 "chlorphenesin": {
  "formula": "C9H11ClO3",
  "mw": "202.63"
 },
 "bisbentiamine": {
  "formula": "C38H42N8O6S2",
  "mw": "770.9"
 },
 "fursultiamine": {
  "formula": "C17H26N4O3S2",
  "mw": "398.5"
 },
 "firocoxib": {
  "formula": "C17H20O5S",
  "mw": "336.4"
 },
 "carprofen": {
  "formula": "C15H12ClNO2",
  "mw": "273.71"
 },
 "ketoprofen": {
  "formula": "C16H14O3",
  "mw": "254.28"
 },
 "imidocarb-dipropionate": {
  "formula": "C25H32N6O5",
  "mw": "496.6"
 },
 "maropitant-citrate": {
  "formula": "C32H40N2O",
  "mw": "468.7"
 },
 "robenacoxib": {
  "formula": "C16H13F4NO2",
  "mw": "327.27"
 },
 "tetrahydro-2-furoic-acid": {
  "formula": "C5H8O3",
  "mw": "116.11"
 },
 "tetrahydro-methyl-2-furoate": {
  "formula": "C6H10O3",
  "mw": "130.14"
 },
 "veratrol": {
  "formula": "C8H10O2",
  "mw": "138.16"
 },
 "pivaloyl-acetonitrile": {
  "formula": "C7H11NO",
  "mw": "125.17"
 },
 "2-ethoxymethylene-malononitrile": {
  "formula": "C6H6N2O",
  "mw": "122.12"
 },
 "n-2-6-dimethylphenyl-1-piperazine-acetamide": {
  "formula": "C14H21N3O",
  "mw": "247.34"
 },
 "guethol": {
  "formula": "C8H10O2",
  "mw": "138.16"
 },
 "5-hydrazinoisophthalic-acid": {
  "formula": "C8H8N2O4",
  "mw": "196.16"
 },
 "5-hydrazinoisophthalic-acid-hcl": {
  "formula": "C8H9ClN2O4",
  "mw": "232.62"
 },
 "5-aminoisophthalic-acid": {
  "formula": "C8H7NO4",
  "mw": "181.15"
 },
 "5-aminoisophthalic-acid-hydrate": {
  "formula": "C8H9NO5",
  "mw": "199.16"
 },
 "trehalose-dihydrate": {
  "formula": "C12H26O13",
  "mw": "378.33"
 },
 "sodium-stearyl-fumarate": {
  "formula": "C22H39NaO4",
  "mw": "390.5"
 },
 "d-galactose": {
  "formula": "C6H12O6",
  "mw": "180.16"
 },
 "potassium-guaiacol-sulphonate": {},
 "drotaverine-hydrochloride": {},
 "prazosin-hydrochloride": {},
 "terazosin-hydrochloride": {},
 "calcium-glycerophosphate": {
  "formula": "C3H7CaO6P",
  "mw": "210.14"
 },
 "tetrahydro-1-2-furoyl-piperazine": {}
};
